// Sample content for local development and design work, used until the
// real Supabase project (cars, tours, reviews tables) is connected. See
// lib/data.ts for the Supabase-first / mock-fallback data access layer, and
// scripts/generate-placeholder-images.mjs + scripts/generate-tour-images.mjs
// for how the referenced image files are produced.

import type { Car, GalleryImage, Review, TourPackage } from "./types";

const carAngleLabels = [
  "Front Three-Quarter",
  "Side Profile",
  "Rear",
  "Interior — Front Seats",
  "Interior — Dashboard",
  "Detail",
];

function carImages(slug: string, make: string, model: string, year: number): GalleryImage[] {
  return carAngleLabels.map((label, i) => ({
    id: `${slug}-img-${i}`,
    url: `/cars/${slug}/${i}.svg`,
    alt: `${year} ${make} ${model} — ${label}`,
    position: i,
  }));
}

const tourAngleLabels = ["Cover", "Landscape", "Group Highlight", "Detail"];

function tourImages(slug: string, title: string): GalleryImage[] {
  return tourAngleLabels.map((label, i) => ({
    id: `${slug}-img-${i}`,
    url: `/tours/${slug}/${i}.svg`,
    alt: `${title} — ${label}`,
    position: i,
  }));
}

// ---- cars -------------------------------------------------------------

export const mockCars: Car[] = [
  {
    id: "car-1",
    slug: "toyota-rav4-2022",
    make: "Toyota",
    model: "RAV4",
    trim: "Adventure AWD",
    year: 2022,
    price: 6850000,
    currency: "ETB",
    mileageKm: 28500,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Magnetic Grey",
    interiorColor: "Black",
    engine: "2.5L 4-cylinder",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Single prior owner, full service history, imported and inspected on arrival — no accident history, tyres and brakes at over 80% life.",
    specSheetUrl: "/spec-sheets/toyota-rav4-2022.pdf",
    isFeatured: true,
    createdAt: "2026-06-02T08:00:00Z",
    images: carImages("toyota-rav4-2022", "Toyota", "RAV4", 2022),
  },
  {
    id: "car-2",
    slug: "toyota-corolla-2021",
    make: "Toyota",
    model: "Corolla",
    trim: "SE",
    year: 2021,
    price: 4250000,
    currency: "ETB",
    mileageKm: 41200,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "sedan",
    status: "available",
    exteriorColor: "Pearl White",
    interiorColor: "Beige",
    engine: "1.8L 4-cylinder",
    drivetrain: "FWD",
    seats: 5,
    doors: 4,
    conditionSummary:
      "Economical daily driver, recently serviced, new brake pads front and rear, clean interior with no odours or stains.",
    specSheetUrl: "/spec-sheets/toyota-corolla-2021.pdf",
    isFeatured: true,
    createdAt: "2026-05-20T08:00:00Z",
    images: carImages("toyota-corolla-2021", "Toyota", "Corolla", 2021),
  },
  {
    id: "car-3",
    slug: "toyota-land-cruiser-prado-2020",
    make: "Toyota",
    model: "Land Cruiser Prado",
    trim: "VX",
    year: 2020,
    price: 11200000,
    currency: "ETB",
    mileageKm: 63400,
    fuelType: "diesel",
    transmission: "automatic",
    bodyType: "suv",
    status: "reserved",
    exteriorColor: "Attitude Black",
    interiorColor: "Black Leather",
    engine: "2.8L Turbo Diesel",
    drivetrain: "4WD",
    seats: 7,
    doors: 5,
    conditionSummary:
      "Built for Ethiopian roads — recently serviced 4WD system, all-terrain tyres at 90% life, tow bar fitted, third-row seating intact.",
    specSheetUrl: "/spec-sheets/toyota-land-cruiser-prado-2020.pdf",
    isFeatured: true,
    createdAt: "2026-04-11T08:00:00Z",
    images: carImages("toyota-land-cruiser-prado-2020", "Toyota", "Land Cruiser Prado", 2020),
  },
  {
    id: "car-4",
    slug: "hyundai-tucson-2023",
    make: "Hyundai",
    model: "Tucson",
    trim: "Signature",
    year: 2023,
    price: 7100000,
    currency: "ETB",
    mileageKm: 15800,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Amazon Grey",
    interiorColor: "Black",
    engine: "2.0L 4-cylinder",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Low mileage, still under manufacturer warranty, panoramic sunroof, full digital cluster — arrives with original delivery documents.",
    specSheetUrl: "/spec-sheets/hyundai-tucson-2023.pdf",
    isFeatured: false,
    createdAt: "2026-06-18T08:00:00Z",
    images: carImages("hyundai-tucson-2023", "Hyundai", "Tucson", 2023),
  },
  {
    id: "car-5",
    slug: "suzuki-vitara-2022",
    make: "Suzuki",
    model: "Vitara",
    trim: "1.5 Full Hybrid",
    year: 2022,
    price: 5450000,
    currency: "ETB",
    mileageKm: 24700,
    fuelType: "hybrid",
    transmission: "automatic",
    bodyType: "suv",
    status: "on_test_drive",
    exteriorColor: "Speedy Blue",
    interiorColor: "Grey",
    engine: "1.5L Hybrid",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Excellent fuel economy for city and highway driving, hybrid battery health confirmed at inspection, compact and easy to park.",
    specSheetUrl: "/spec-sheets/suzuki-vitara-2022.pdf",
    isFeatured: false,
    createdAt: "2026-06-25T08:00:00Z",
    images: carImages("suzuki-vitara-2022", "Suzuki", "Vitara", 2022),
  },
  {
    id: "car-6",
    slug: "nissan-xtrail-2020",
    make: "Nissan",
    model: "X-Trail",
    trim: "VL",
    year: 2020,
    price: 6100000,
    currency: "ETB",
    mileageKm: 58900,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Brilliant Silver",
    interiorColor: "Black",
    engine: "2.5L 4-cylinder",
    drivetrain: "AWD",
    seats: 7,
    doors: 5,
    conditionSummary:
      "Spacious 7-seat family SUV, third row folds flat, recently fitted new battery and cabin filter.",
    specSheetUrl: "/spec-sheets/nissan-xtrail-2020.pdf",
    isFeatured: false,
    createdAt: "2026-05-05T08:00:00Z",
    images: carImages("nissan-xtrail-2020", "Nissan", "X-Trail", 2020),
  },
  {
    id: "car-7",
    slug: "mitsubishi-pajero-2019",
    make: "Mitsubishi",
    model: "Pajero Sport",
    trim: "GT-Premium 4WD",
    year: 2019,
    price: 7850000,
    currency: "ETB",
    mileageKm: 71300,
    fuelType: "diesel",
    transmission: "automatic",
    bodyType: "suv",
    status: "sold",
    exteriorColor: "Titanium Grey",
    interiorColor: "Black Leather",
    engine: "2.4L Turbo Diesel",
    drivetrain: "4WD",
    seats: 7,
    doors: 5,
    conditionSummary:
      "Sold — kept for reference. Rugged off-road capability, tested and serviced 4WD low-range transfer case, tow-rated for trailers.",
    specSheetUrl: "/spec-sheets/mitsubishi-pajero-2019.pdf",
    isFeatured: false,
    createdAt: "2026-03-14T08:00:00Z",
    images: carImages("mitsubishi-pajero-2019", "Mitsubishi", "Pajero Sport", 2019),
  },
  {
    id: "car-8",
    slug: "kia-sportage-2022",
    make: "Kia",
    model: "Sportage",
    trim: "GT-Line",
    year: 2022,
    price: 6400000,
    currency: "ETB",
    mileageKm: 19200,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "coming_soon",
    exteriorColor: "Interstellar Grey",
    interiorColor: "Black",
    engine: "1.6L Turbo",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Currently in transit — arriving next shipment. Reserve now with a refundable deposit to secure first viewing.",
    specSheetUrl: "/spec-sheets/kia-sportage-2022.pdf",
    isFeatured: true,
    createdAt: "2026-07-01T08:00:00Z",
    images: carImages("kia-sportage-2022", "Kia", "Sportage", 2022),
  },
];

// ---- tours ----------------------------------------------------------------

export const mockTours: TourPackage[] = [
  {
    id: "tour-1",
    slug: "simien-mountains-trek",
    title: "Simien Mountains Trek",
    destination: "Simien Mountains National Park",
    category: "nature",
    durationDays: 5,
    groupSizeMax: 12,
    difficulty: "moderate",
    price: 45000,
    currency: "ETB",
    summary:
      "Trek the jagged escarpments of a UNESCO World Heritage site, camping under the stars with close encounters with Gelada baboons and Walia ibex.",
    itinerary: [
      { day: 1, title: "Addis Ababa to Debark", description: "Fly or drive to Gondar, transfer to Debark, park briefing and gear check." },
      { day: 2, title: "Sankaber to Geech", description: "Trek through highland plateau scenery, camp near Jinbar waterfall." },
      { day: 3, title: "Geech to Chennek", description: "Ridge walk with Gelada baboon troops, views over the escarpment." },
      { day: 4, title: "Chennek exploration", description: "Optional summit attempt or Walia ibex viewing, second night at Chennek." },
      { day: 5, title: "Return to Debark, transfer to Gondar", description: "Descend, farewell lunch, transfer for onward travel." },
    ],
    inclusions: ["Licensed English-speaking guide", "Park entry & scout fees", "Camping equipment", "All meals during trek", "4WD transport within the park"],
    exclusions: ["Flights to/from Gondar", "Personal trekking gear", "Tips", "Travel insurance"],
    isFeatured: true,
    createdAt: "2026-05-01T08:00:00Z",
    images: tourImages("simien-mountains-trek", "Simien Mountains Trek"),
  },
  {
    id: "tour-2",
    slug: "lalibela-rock-churches",
    title: "Lalibela Rock-Hewn Churches",
    destination: "Lalibela",
    category: "religious",
    durationDays: 3,
    groupSizeMax: 15,
    difficulty: "easy",
    price: 28000,
    currency: "ETB",
    summary:
      "Walk among 12th-century churches carved directly into volcanic rock, a living pilgrimage site and one of Ethiopia's most iconic landmarks.",
    itinerary: [
      { day: 1, title: "Arrival in Lalibela", description: "Transfer to hotel, afternoon visit to the Northern cluster of churches." },
      { day: 2, title: "Southern cluster & Bete Giyorgis", description: "Full day exploring the Southeastern cluster, ending at the famed Church of St. George." },
      { day: 3, title: "Yemrehanna Kristos & departure", description: "Optional excursion to the cave church, then transfer for departure." },
    ],
    inclusions: ["Licensed English-speaking guide", "Church entry fees", "Airport/hotel transfers", "Daily breakfast"],
    exclusions: ["Flights to/from Lalibela", "Lunch & dinner", "Tips", "Travel insurance"],
    isFeatured: true,
    createdAt: "2026-05-08T08:00:00Z",
    images: tourImages("lalibela-rock-churches", "Lalibela Rock-Hewn Churches"),
  },
  {
    id: "tour-3",
    slug: "danakil-depression-expedition",
    title: "Danakil Depression Expedition",
    destination: "Danakil Depression, Afar Region",
    category: "adventure",
    durationDays: 4,
    groupSizeMax: 8,
    difficulty: "challenging",
    price: 52000,
    currency: "ETB",
    summary:
      "One of the hottest, lowest places on Earth — active volcanoes, technicolor sulfur springs, and vast salt flats below sea level.",
    itinerary: [
      { day: 1, title: "Mekele to Hamedela", description: "Drive into the depression, visit salt flats at sunset." },
      { day: 2, title: "Dallol & salt lakes", description: "Sunrise at Dallol's sulfur springs, afternoon at the salt caravans of Lake Karum." },
      { day: 3, title: "Erta Ale volcano", description: "Drive to base camp, evening trek to the rim of an active lava lake." },
      { day: 4, title: "Return to Mekele", description: "Descend before sunrise heat, long drive back with rest stops." },
    ],
    inclusions: ["4WD convoy with driver-guides", "Armed scout escort (regional requirement)", "Camping equipment", "All meals", "Bottled water"],
    exclusions: ["Flights to/from Mekele", "Tips", "Travel insurance", "Personal medication"],
    isFeatured: true,
    createdAt: "2026-06-10T08:00:00Z",
    images: tourImages("danakil-depression-expedition", "Danakil Depression Expedition"),
  },
  {
    id: "tour-4",
    slug: "omo-valley-cultural-tour",
    title: "Omo Valley Cultural Tour",
    destination: "South Omo Valley",
    category: "cultural",
    durationDays: 6,
    groupSizeMax: 10,
    difficulty: "moderate",
    price: 60000,
    currency: "ETB",
    summary:
      "Meet the Hamar, Mursi, Karo and Dassanech communities of the lower Omo Valley, one of Africa's most culturally diverse regions.",
    itinerary: [
      { day: 1, title: "Addis Ababa to Arba Minch", description: "Fly to Arba Minch, boat trip on Lake Chamo for hippos and crocodiles." },
      { day: 2, title: "Arba Minch to Jinka", description: "Drive through the Rift Valley, visit the South Omo Museum in Jinka." },
      { day: 3, title: "Mursi village visit", description: "Excursion into Mago National Park to visit a Mursi community." },
      { day: 4, title: "Turmi & Hamar culture", description: "Drive to Turmi, visit a Hamar village and, seasonally, a bull-jumping ceremony." },
      { day: 5, title: "Omorate & Dassanech", description: "Cross the Omo River to a Dassanech village near the Kenyan border." },
      { day: 6, title: "Return to Arba Minch, fly to Addis Ababa", description: "Morning market visit, transfer to airport." },
    ],
    inclusions: ["Licensed English-speaking guide", "4WD transport", "Village visit fees", "All meals during the tour", "Domestic flight Arba Minch–Addis"],
    exclusions: ["Flight Addis Ababa–Arba Minch", "Tips", "Travel insurance", "Photography fees paid directly to communities"],
    isFeatured: false,
    createdAt: "2026-04-22T08:00:00Z",
    images: tourImages("omo-valley-cultural-tour", "Omo Valley Cultural Tour"),
  },
  {
    id: "tour-5",
    slug: "bale-mountains-wildlife-safari",
    title: "Bale Mountains Wildlife Safari",
    destination: "Bale Mountains National Park",
    category: "wildlife",
    durationDays: 4,
    groupSizeMax: 10,
    difficulty: "moderate",
    price: 38000,
    currency: "ETB",
    summary:
      "Ethiopia's premier wildlife destination — the best chance in the country to see the rare Ethiopian wolf, plus Afro-alpine moorland scenery.",
    itinerary: [
      { day: 1, title: "Addis Ababa to Dinsho", description: "Drive to the park headquarters, afternoon walk in Gaysay Valley for mountain nyala." },
      { day: 2, title: "Sanetti Plateau", description: "Full day on the high plateau tracking Ethiopian wolves, visit to the Harenna Forest edge." },
      { day: 3, title: "Harenna Forest", description: "Descend into cloud forest, birdwatching and forest coffee visit." },
      { day: 4, title: "Return to Addis Ababa", description: "Morning game drive, drive back to the capital." },
    ],
    inclusions: ["Licensed naturalist guide", "Park entry & scout fees", "4WD transport", "All meals", "Accommodation (lodge/camping mix)"],
    exclusions: ["Tips", "Travel insurance", "Alcoholic beverages"],
    isFeatured: false,
    createdAt: "2026-06-05T08:00:00Z",
    images: tourImages("bale-mountains-wildlife-safari", "Bale Mountains Wildlife Safari"),
  },
  {
    id: "tour-6",
    slug: "axum-gondar-historical-route",
    title: "Axum & Gondar Historical Route",
    destination: "Axum, Gondar",
    category: "historical",
    durationDays: 5,
    groupSizeMax: 14,
    difficulty: "easy",
    price: 42000,
    currency: "ETB",
    summary:
      "Trace Ethiopia's imperial history from the ancient obelisks of Axum to the castles of Gondar, Africa's 'Camelot'.",
    itinerary: [
      { day: 1, title: "Arrival in Axum", description: "Visit the stelae field and the Church of St. Mary of Zion." },
      { day: 2, title: "Axum exploration", description: "Queen of Sheba's Bath, ancient tombs, and the Ezana Stone." },
      { day: 3, title: "Fly to Gondar", description: "Visit the Royal Enclosure and Fasilides' Castle complex." },
      { day: 4, title: "Debre Berhan Selassie & Lake Tana", description: "Visit the painted church, afternoon boat trip to the island monasteries of Lake Tana." },
      { day: 5, title: "Departure", description: "Free morning, transfer to airport." },
    ],
    inclusions: ["Licensed English-speaking guide", "Site entry fees", "Domestic flight Axum–Gondar", "Daily breakfast", "Airport transfers"],
    exclusions: ["Flights to/from Axum and from Gondar", "Lunch & dinner", "Tips", "Travel insurance"],
    isFeatured: false,
    createdAt: "2026-03-30T08:00:00Z",
    images: tourImages("axum-gondar-historical-route", "Axum & Gondar Historical Route"),
  },
];

// ---- reviews ----------------------------------------------------------------

export const mockReviews: Review[] = [
  {
    id: "review-1",
    customerName: "Selamawit T.",
    rating: 5,
    body: "Bought a RAV4 through NUR LA and the whole process was transparent — they showed me the inspection report before I paid anything. Delivered clean and exactly as described.",
    itemLabel: "2022 Toyota RAV4",
    createdAt: "2026-06-20T08:00:00Z",
  },
  {
    id: "review-2",
    customerName: "Dawit K.",
    rating: 5,
    body: "The Simien Mountains trek was the highlight of our trip to Ethiopia. Our guide knew every ridge and the camping setup was better than I expected.",
    itemLabel: "Simien Mountains Trek",
    createdAt: "2026-06-15T08:00:00Z",
  },
  {
    id: "review-3",
    customerName: "Marcus H.",
    rating: 5,
    body: "Danakil was intense but the team's logistics were flawless — never once felt unsafe, even at Erta Ale at night. Worth every birr.",
    itemLabel: "Danakil Depression Expedition",
    createdAt: "2026-06-08T08:00:00Z",
  },
  {
    id: "review-4",
    customerName: "Hanna G.",
    rating: 4,
    body: "Good communication throughout the import process for my Tucson. Took a bit longer than the original estimate but they kept me updated the whole way.",
    itemLabel: "2023 Hyundai Tucson",
    createdAt: "2026-05-28T08:00:00Z",
  },
  {
    id: "review-5",
    customerName: "Yosef A.",
    rating: 5,
    body: "Traded in my old Corolla toward a Land Cruiser Prado — fair valuation, no pressure, and the paperwork was handled for me.",
    itemLabel: "2020 Toyota Land Cruiser Prado",
    createdAt: "2026-05-12T08:00:00Z",
  },
  {
    id: "review-6",
    customerName: "Liya M.",
    rating: 5,
    body: "Lalibela with NUR LA was so well organized — early access before the crowds arrived, and our guide's explanations of the church history were excellent.",
    itemLabel: "Lalibela Rock-Hewn Churches",
    createdAt: "2026-04-30T08:00:00Z",
  },
];
