// Sample content for local development and design work, used until the
// real Supabase project (cars, tours, reviews tables) is connected. See
// lib/data.ts for the Supabase-first / mock-fallback data access layer, and
// scripts/generate-placeholder-images.mjs + scripts/generate-tour-images.mjs
// for how the referenced image files are produced.

import type { Car, GalleryImage, Review, TourPackage } from "./types";

const carAngleLabels = [
  "Front Three-Quarter",
  "Side Profile",
  "Rear",
  "Interior — Front Seats",
  "Interior — Dashboard",
  "Detail",
];

export interface PhotoCredit {
  slug: string;
  fileTitle: string;
  url: string;
  sourcePageUrl: string;
  license: string;
  licenseVerified: boolean;
}

// Reference photos for the primary (card) image of each demo car, sourced
// from Wikimedia Commons — the same set used on the Yemareyam Car Import
// site. Trim/color may differ slightly from the listed vehicle — these are
// mockup/reference photography, not the actual car in stock. See
// app/credits/page.tsx (linked from the footer) for the full, visitor-facing
// attribution required by the CC licenses below; keep that page in sync
// with this list. Entries flagged licenseVerified: false had an uncertain
// license at sourcing time and must be checked on the source page before
// any real production use.
export const photoCredits: PhotoCredit[] = [
  { slug: "toyota-rav4-2022", fileTitle: "Toyota_RAV4_2.5_LTD_HEV_2022.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota_RAV4_2.5_LTD_HEV_2022.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Toyota_RAV4_2.5_LTD_HEV_2022.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "toyota-corolla-2021", fileTitle: "2021_Toyota_Corolla_SE_Hatchback.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Toyota_Corolla_SE_Hatchback.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2021_Toyota_Corolla_SE_Hatchback.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "toyota-land-cruiser-prado-2020", fileTitle: "Toyota_Land_Cruiser_Prado_J150_4.0_VX_2020.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota_Land_Cruiser_Prado_J150_4.0_VX_2020.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Toyota_Land_Cruiser_Prado_J150_4.0_VX_2020.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "hyundai-tucson-2023", fileTitle: "2023_Hyundai_Tucson_Signature_(India)_front_view.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2023_Hyundai_Tucson_Signature_%28India%29_front_view.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2023_Hyundai_Tucson_Signature_(India)_front_view.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "hyundai-i10-2019", fileTitle: "Hyundai_i10_(48813787728).jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Hyundai_i10_%2848813787728%29.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Hyundai_i10_(48813787728).jpg", license: "Unconfirmed — verify on source page before production use", licenseVerified: false },
  { slug: "suzuki-dzire-2021", fileTitle: "Maruti_Suzuki_Dzire_VXi_VVT_(front).JPG", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Maruti_Suzuki_Dzire_VXi_VVT_%28front%29.JPG", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Maruti_Suzuki_Dzire_VXi_VVT_(front).JPG", license: "CC BY 3.0", licenseVerified: true },
  { slug: "suzuki-vitara-2022", fileTitle: "2022_Suzuki_Vitara_1.5_Full_Hybrid.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2022_Suzuki_Vitara_1.5_Full_Hybrid.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2022_Suzuki_Vitara_1.5_Full_Hybrid.jpg", license: "CC BY 2.0", licenseVerified: true },
  { slug: "nissan-xtrail-2020", fileTitle: "2020_Nissan_X-Trail_VL_facelift_(front),_West_Surabaya.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Nissan_X-Trail_VL_facelift_%28front%29%2C_West_Surabaya.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2020_Nissan_X-Trail_VL_facelift_(front),_West_Surabaya.jpg", license: "Unconfirmed — verify on source page before production use", licenseVerified: false },
  { slug: "mitsubishi-pajero-2019", fileTitle: "2019_Mitsubishi_Pajero_Sport_GT-Premium_4WD.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2019_Mitsubishi_Pajero_Sport_GT-Premium_4WD.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2019_Mitsubishi_Pajero_Sport_GT-Premium_4WD.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "lexus-rx350-2021", fileTitle: "Lexus_RX_350_2021.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Lexus_RX_350_2021.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Lexus_RX_350_2021.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "kia-sportage-2022", fileTitle: "2022_Kia_Sportage.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2022_Kia_Sportage.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2022_Kia_Sportage.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "ford-ranger-2021", fileTitle: "2021_Ford_Ranger_XL,_front_6.1.22.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Ford_Ranger_XL%2C_front_6.1.22.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2021_Ford_Ranger_XL,_front_6.1.22.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "honda-crv-2023", fileTitle: "2023_Honda_CR-V_front_end.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2023_Honda_CR-V_front_end.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2023_Honda_CR-V_front_end.jpg", license: "Unconfirmed — verify on source page before production use", licenseVerified: false },
  { slug: "volkswagen-tiguan-2020", fileTitle: "2020_Volkswagen_Tiguan_au_SIAM_2020.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Volkswagen_Tiguan_au_SIAM_2020.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2020_Volkswagen_Tiguan_au_SIAM_2020.jpg", license: "Public Domain", licenseVerified: true },
];

function carImages(slug: string, make: string, model: string, year: number): GalleryImage[] {
  const credit = photoCredits.find((c) => c.slug === slug);
  return carAngleLabels.map((label, i) => {
    if (i === 0 && credit) {
      return {
        id: `${slug}-img-0`,
        url: credit.url,
        alt: `${year} ${make} ${model} — reference photo (trim/color may vary)`,
        position: 0,
      };
    }
    return {
      id: `${slug}-img-${i}`,
      url: `/cars/${slug}/${i}.svg`,
      alt: `${year} ${make} ${model} — ${label}`,
      position: i,
    };
  });
}

const tourAngleLabels = ["Cover", "Landscape", "Group Highlight", "Detail"];

function tourImages(slug: string, title: string): GalleryImage[] {
  return tourAngleLabels.map((label, i) => ({
    id: `${slug}-img-${i}`,
    url: `/tours/${slug}/${i}.svg`,
    alt: `${title} — ${label}`,
    position: i,
  }));
}

// ---- cars -------------------------------------------------------------

export const mockCars: Car[] = [
  {
    id: "car-1",
    slug: "toyota-rav4-2022",
    make: "Toyota",
    model: "RAV4",
    trim: "Adventure AWD",
    year: 2022,
    price: 6850000,
    currency: "ETB",
    mileageKm: 28500,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Magnetic Grey",
    interiorColor: "Black",
    engine: "2.5L 4-cylinder",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Single prior owner, full service history, imported and inspected on arrival — no accident history, tyres and brakes at over 80% life.",
    specSheetUrl: "/spec-sheets/toyota-rav4-2022.pdf",
    isFeatured: true,
    createdAt: "2026-06-02T08:00:00Z",
    images: carImages("toyota-rav4-2022", "Toyota", "RAV4", 2022),
  },
  {
    id: "car-2",
    slug: "toyota-corolla-2021",
    make: "Toyota",
    model: "Corolla",
    trim: "SE",
    year: 2021,
    price: 4250000,
    currency: "ETB",
    mileageKm: 41200,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "sedan",
    status: "available",
    exteriorColor: "Pearl White",
    interiorColor: "Beige",
    engine: "1.8L 4-cylinder",
    drivetrain: "FWD",
    seats: 5,
    doors: 4,
    conditionSummary:
      "Economical daily driver, recently serviced, new brake pads front and rear, clean interior with no odours or stains.",
    specSheetUrl: "/spec-sheets/toyota-corolla-2021.pdf",
    isFeatured: true,
    createdAt: "2026-05-20T08:00:00Z",
    images: carImages("toyota-corolla-2021", "Toyota", "Corolla", 2021),
  },
  {
    id: "car-3",
    slug: "toyota-land-cruiser-prado-2020",
    make: "Toyota",
    model: "Land Cruiser Prado",
    trim: "VX",
    year: 2020,
    price: 11200000,
    currency: "ETB",
    mileageKm: 63400,
    fuelType: "diesel",
    transmission: "automatic",
    bodyType: "suv",
    status: "reserved",
    exteriorColor: "Attitude Black",
    interiorColor: "Black Leather",
    engine: "2.8L Turbo Diesel",
    drivetrain: "4WD",
    seats: 7,
    doors: 5,
    conditionSummary:
      "Built for Ethiopian roads — recently serviced 4WD system, all-terrain tyres at 90% life, tow bar fitted, third-row seating intact.",
    specSheetUrl: "/spec-sheets/toyota-land-cruiser-prado-2020.pdf",
    isFeatured: true,
    createdAt: "2026-04-11T08:00:00Z",
    images: carImages("toyota-land-cruiser-prado-2020", "Toyota", "Land Cruiser Prado", 2020),
  },
  {
    id: "car-4",
    slug: "hyundai-tucson-2023",
    make: "Hyundai",
    model: "Tucson",
    trim: "Signature",
    year: 2023,
    price: 7100000,
    currency: "ETB",
    mileageKm: 15800,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Amazon Grey",
    interiorColor: "Black",
    engine: "2.0L 4-cylinder",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Low mileage, still under manufacturer warranty, panoramic sunroof, full digital cluster — arrives with original delivery documents.",
    specSheetUrl: "/spec-sheets/hyundai-tucson-2023.pdf",
    isFeatured: false,
    createdAt: "2026-06-18T08:00:00Z",
    images: carImages("hyundai-tucson-2023", "Hyundai", "Tucson", 2023),
  },
  {
    id: "car-5",
    slug: "suzuki-vitara-2022",
    make: "Suzuki",
    model: "Vitara",
    trim: "1.5 Full Hybrid",
    year: 2022,
    price: 5450000,
    currency: "ETB",
    mileageKm: 24700,
    fuelType: "hybrid",
    transmission: "automatic",
    bodyType: "suv",
    status: "on_test_drive",
    exteriorColor: "Speedy Blue",
    interiorColor: "Grey",
    engine: "1.5L Hybrid",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Excellent fuel economy for city and highway driving, hybrid battery health confirmed at inspection, compact and easy to park.",
    specSheetUrl: "/spec-sheets/suzuki-vitara-2022.pdf",
    isFeatured: false,
    createdAt: "2026-06-25T08:00:00Z",
    images: carImages("suzuki-vitara-2022", "Suzuki", "Vitara", 2022),
  },
  {
    id: "car-6",
    slug: "nissan-xtrail-2020",
    make: "Nissan",
    model: "X-Trail",
    trim: "VL",
    year: 2020,
    price: 6100000,
    currency: "ETB",
    mileageKm: 58900,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Brilliant Silver",
    interiorColor: "Black",
    engine: "2.5L 4-cylinder",
    drivetrain: "AWD",
    seats: 7,
    doors: 5,
    conditionSummary:
      "Spacious 7-seat family SUV, third row folds flat, recently fitted new battery and cabin filter.",
    specSheetUrl: "/spec-sheets/nissan-xtrail-2020.pdf",
    isFeatured: false,
    createdAt: "2026-05-05T08:00:00Z",
    images: carImages("nissan-xtrail-2020", "Nissan", "X-Trail", 2020),
  },
  {
    id: "car-7",
    slug: "mitsubishi-pajero-2019",
    make: "Mitsubishi",
    model: "Pajero Sport",
    trim: "GT-Premium 4WD",
    year: 2019,
    price: 7850000,
    currency: "ETB",
    mileageKm: 71300,
    fuelType: "diesel",
    transmission: "automatic",
    bodyType: "suv",
    status: "sold",
    exteriorColor: "Titanium Grey",
    interiorColor: "Black Leather",
    engine: "2.4L Turbo Diesel",
    drivetrain: "4WD",
    seats: 7,
    doors: 5,
    conditionSummary:
      "Sold — kept for reference. Rugged off-road capability, tested and serviced 4WD low-range transfer case, tow-rated for trailers.",
    specSheetUrl: "/spec-sheets/mitsubishi-pajero-2019.pdf",
    isFeatured: false,
    createdAt: "2026-03-14T08:00:00Z",
    images: carImages("mitsubishi-pajero-2019", "Mitsubishi", "Pajero Sport", 2019),
  },
  {
    id: "car-8",
    slug: "kia-sportage-2022",
    make: "Kia",
    model: "Sportage",
    trim: "GT-Line",
    year: 2022,
    price: 6400000,
    currency: "ETB",
    mileageKm: 19200,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "coming_soon",
    exteriorColor: "Interstellar Grey",
    interiorColor: "Black",
    engine: "1.6L Turbo",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Currently in transit — arriving next shipment. Reserve now with a refundable deposit to secure first viewing.",
    specSheetUrl: "/spec-sheets/kia-sportage-2022.pdf",
    isFeatured: true,
    createdAt: "2026-07-01T08:00:00Z",
    images: carImages("kia-sportage-2022", "Kia", "Sportage", 2022),
  },
  {
    id: "car-9",
    slug: "hyundai-i10-2019",
    make: "Hyundai",
    model: "i10",
    trim: "Magna",
    year: 2019,
    price: 2350000,
    currency: "ETB",
    mileageKm: 63400,
    fuelType: "petrol",
    transmission: "manual",
    bodyType: "hatchback",
    status: "available",
    exteriorColor: "Fiery Red",
    interiorColor: "Grey",
    engine: "1.2L 4-cylinder",
    drivetrain: "FWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Affordable, economical city car — recently serviced, new tyres all round, ideal first import for budget-conscious buyers.",
    specSheetUrl: "/spec-sheets/hyundai-i10-2019.pdf",
    isFeatured: false,
    createdAt: "2026-06-01T08:00:00Z",
    images: carImages("hyundai-i10-2019", "Hyundai", "i10", 2019),
  },
  {
    id: "car-10",
    slug: "suzuki-dzire-2021",
    make: "Suzuki",
    model: "Dzire",
    trim: "VXI",
    year: 2021,
    price: 3100000,
    currency: "ETB",
    mileageKm: 34700,
    fuelType: "petrol",
    transmission: "manual",
    bodyType: "sedan",
    status: "on_test_drive",
    exteriorColor: "Pearl Arctic White",
    interiorColor: "Beige",
    engine: "1.2L 4-cylinder",
    drivetrain: "FWD",
    seats: 5,
    doors: 4,
    conditionSummary:
      "Compact and fuel-efficient sedan, well suited to city driving — full inspection completed, no mechanical issues found.",
    specSheetUrl: "/spec-sheets/suzuki-dzire-2021.pdf",
    isFeatured: false,
    createdAt: "2026-06-12T08:00:00Z",
    images: carImages("suzuki-dzire-2021", "Suzuki", "Dzire", 2021),
  },
  {
    id: "car-11",
    slug: "lexus-rx350-2021",
    make: "Lexus",
    model: "RX 350",
    trim: "F Sport",
    year: 2021,
    price: 12900000,
    currency: "ETB",
    mileageKm: 31600,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "reserved",
    exteriorColor: "Nori Green",
    interiorColor: "Black Leather",
    engine: "3.5L V6",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Premium SUV in excellent condition, full service history, no accident history — a step up for buyers wanting luxury and reliability.",
    specSheetUrl: "/spec-sheets/lexus-rx350-2021.pdf",
    isFeatured: true,
    createdAt: "2026-06-08T08:00:00Z",
    images: carImages("lexus-rx350-2021", "Lexus", "RX 350", 2021),
  },
  {
    id: "car-12",
    slug: "ford-ranger-2021",
    make: "Ford",
    model: "Ranger",
    trim: "XLT",
    year: 2021,
    price: 6700000,
    currency: "ETB",
    mileageKm: 39800,
    fuelType: "diesel",
    transmission: "automatic",
    bodyType: "pickup",
    status: "available",
    exteriorColor: "Meteor Grey",
    interiorColor: "Black",
    engine: "2.0L Bi-Turbo Diesel",
    drivetrain: "4WD",
    seats: 5,
    doors: 4,
    conditionSummary:
      "Capable work and off-road pickup, tow bar fitted, bed liner installed, recently serviced 4WD system.",
    specSheetUrl: "/spec-sheets/ford-ranger-2021.pdf",
    isFeatured: false,
    createdAt: "2026-05-15T08:00:00Z",
    images: carImages("ford-ranger-2021", "Ford", "Ranger", 2021),
  },
  {
    id: "car-13",
    slug: "honda-crv-2023",
    make: "Honda",
    model: "CR-V",
    trim: "EX-L",
    year: 2023,
    price: 7400000,
    currency: "ETB",
    mileageKm: 0,
    fuelType: "hybrid",
    transmission: "automatic",
    bodyType: "suv",
    status: "coming_soon",
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Black Leather",
    engine: "2.0L Hybrid",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Currently in transit and undergoing pre-listing inspection and detailing. Full condition summary will be published once it arrives.",
    specSheetUrl: "/spec-sheets/honda-crv-2023.pdf",
    isFeatured: true,
    createdAt: "2026-07-10T08:00:00Z",
    images: carImages("honda-crv-2023", "Honda", "CR-V", 2023),
  },
  {
    id: "car-14",
    slug: "volkswagen-tiguan-2020",
    make: "Volkswagen",
    model: "Tiguan",
    trim: "SE",
    year: 2020,
    price: 5100000,
    currency: "ETB",
    mileageKm: 47600,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "crossover",
    status: "available",
    exteriorColor: "Deep Black Pearl",
    interiorColor: "Titan Black",
    engine: "2.0L Turbo",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    conditionSummary:
      "Well-equipped family crossover, recently serviced, clean title, no accident history.",
    specSheetUrl: "/spec-sheets/volkswagen-tiguan-2020.pdf",
    isFeatured: false,
    createdAt: "2026-05-22T08:00:00Z",
    images: carImages("volkswagen-tiguan-2020", "Volkswagen", "Tiguan", 2020),
  },
];

// ---- tours ----------------------------------------------------------------

export const mockTours: TourPackage[] = [
  {
    id: "tour-1",
    slug: "simien-mountains-trek",
    title: "Simien Mountains Trek",
    destination: "Simien Mountains National Park",
    category: "nature",
    durationDays: 5,
    groupSizeMax: 12,
    difficulty: "moderate",
    price: 45000,
    currency: "ETB",
    summary:
      "Trek the jagged escarpments of a UNESCO World Heritage site, camping under the stars with close encounters with Gelada baboons and Walia ibex.",
    itinerary: [
      { day: 1, title: "Addis Ababa to Debark", description: "Fly or drive to Gondar, transfer to Debark, park briefing and gear check." },
      { day: 2, title: "Sankaber to Geech", description: "Trek through highland plateau scenery, camp near Jinbar waterfall." },
      { day: 3, title: "Geech to Chennek", description: "Ridge walk with Gelada baboon troops, views over the escarpment." },
      { day: 4, title: "Chennek exploration", description: "Optional summit attempt or Walia ibex viewing, second night at Chennek." },
      { day: 5, title: "Return to Debark, transfer to Gondar", description: "Descend, farewell lunch, transfer for onward travel." },
    ],
    inclusions: ["Licensed English-speaking guide", "Park entry & scout fees", "Camping equipment", "All meals during trek", "4WD transport within the park"],
    exclusions: ["Flights to/from Gondar", "Personal trekking gear", "Tips", "Travel insurance"],
    isFeatured: true,
    createdAt: "2026-05-01T08:00:00Z",
    images: tourImages("simien-mountains-trek", "Simien Mountains Trek"),
  },
  {
    id: "tour-2",
    slug: "lalibela-rock-churches",
    title: "Lalibela Rock-Hewn Churches",
    destination: "Lalibela",
    category: "religious",
    durationDays: 3,
    groupSizeMax: 15,
    difficulty: "easy",
    price: 28000,
    currency: "ETB",
    summary:
      "Walk among 12th-century churches carved directly into volcanic rock, a living pilgrimage site and one of Ethiopia's most iconic landmarks.",
    itinerary: [
      { day: 1, title: "Arrival in Lalibela", description: "Transfer to hotel, afternoon visit to the Northern cluster of churches." },
      { day: 2, title: "Southern cluster & Bete Giyorgis", description: "Full day exploring the Southeastern cluster, ending at the famed Church of St. George." },
      { day: 3, title: "Yemrehanna Kristos & departure", description: "Optional excursion to the cave church, then transfer for departure." },
    ],
    inclusions: ["Licensed English-speaking guide", "Church entry fees", "Airport/hotel transfers", "Daily breakfast"],
    exclusions: ["Flights to/from Lalibela", "Lunch & dinner", "Tips", "Travel insurance"],
    isFeatured: true,
    createdAt: "2026-05-08T08:00:00Z",
    images: tourImages("lalibela-rock-churches", "Lalibela Rock-Hewn Churches"),
  },
  {
    id: "tour-3",
    slug: "danakil-depression-expedition",
    title: "Danakil Depression Expedition",
    destination: "Danakil Depression, Afar Region",
    category: "adventure",
    durationDays: 4,
    groupSizeMax: 8,
    difficulty: "challenging",
    price: 52000,
    currency: "ETB",
    summary:
      "One of the hottest, lowest places on Earth — active volcanoes, technicolor sulfur springs, and vast salt flats below sea level.",
    itinerary: [
      { day: 1, title: "Mekele to Hamedela", description: "Drive into the depression, visit salt flats at sunset." },
      { day: 2, title: "Dallol & salt lakes", description: "Sunrise at Dallol's sulfur springs, afternoon at the salt caravans of Lake Karum." },
      { day: 3, title: "Erta Ale volcano", description: "Drive to base camp, evening trek to the rim of an active lava lake." },
      { day: 4, title: "Return to Mekele", description: "Descend before sunrise heat, long drive back with rest stops." },
    ],
    inclusions: ["4WD convoy with driver-guides", "Armed scout escort (regional requirement)", "Camping equipment", "All meals", "Bottled water"],
    exclusions: ["Flights to/from Mekele", "Tips", "Travel insurance", "Personal medication"],
    isFeatured: true,
    createdAt: "2026-06-10T08:00:00Z",
    images: tourImages("danakil-depression-expedition", "Danakil Depression Expedition"),
  },
  {
    id: "tour-4",
    slug: "omo-valley-cultural-tour",
    title: "Omo Valley Cultural Tour",
    destination: "South Omo Valley",
    category: "cultural",
    durationDays: 6,
    groupSizeMax: 10,
    difficulty: "moderate",
    price: 60000,
    currency: "ETB",
    summary:
      "Meet the Hamar, Mursi, Karo and Dassanech communities of the lower Omo Valley, one of Africa's most culturally diverse regions.",
    itinerary: [
      { day: 1, title: "Addis Ababa to Arba Minch", description: "Fly to Arba Minch, boat trip on Lake Chamo for hippos and crocodiles." },
      { day: 2, title: "Arba Minch to Jinka", description: "Drive through the Rift Valley, visit the South Omo Museum in Jinka." },
      { day: 3, title: "Mursi village visit", description: "Excursion into Mago National Park to visit a Mursi community." },
      { day: 4, title: "Turmi & Hamar culture", description: "Drive to Turmi, visit a Hamar village and, seasonally, a bull-jumping ceremony." },
      { day: 5, title: "Omorate & Dassanech", description: "Cross the Omo River to a Dassanech village near the Kenyan border." },
      { day: 6, title: "Return to Arba Minch, fly to Addis Ababa", description: "Morning market visit, transfer to airport." },
    ],
    inclusions: ["Licensed English-speaking guide", "4WD transport", "Village visit fees", "All meals during the tour", "Domestic flight Arba Minch–Addis"],
    exclusions: ["Flight Addis Ababa–Arba Minch", "Tips", "Travel insurance", "Photography fees paid directly to communities"],
    isFeatured: false,
    createdAt: "2026-04-22T08:00:00Z",
    images: tourImages("omo-valley-cultural-tour", "Omo Valley Cultural Tour"),
  },
  {
    id: "tour-5",
    slug: "bale-mountains-wildlife-safari",
    title: "Bale Mountains Wildlife Safari",
    destination: "Bale Mountains National Park",
    category: "wildlife",
    durationDays: 4,
    groupSizeMax: 10,
    difficulty: "moderate",
    price: 38000,
    currency: "ETB",
    summary:
      "Ethiopia's premier wildlife destination — the best chance in the country to see the rare Ethiopian wolf, plus Afro-alpine moorland scenery.",
    itinerary: [
      { day: 1, title: "Addis Ababa to Dinsho", description: "Drive to the park headquarters, afternoon walk in Gaysay Valley for mountain nyala." },
      { day: 2, title: "Sanetti Plateau", description: "Full day on the high plateau tracking Ethiopian wolves, visit to the Harenna Forest edge." },
      { day: 3, title: "Harenna Forest", description: "Descend into cloud forest, birdwatching and forest coffee visit." },
      { day: 4, title: "Return to Addis Ababa", description: "Morning game drive, drive back to the capital." },
    ],
    inclusions: ["Licensed naturalist guide", "Park entry & scout fees", "4WD transport", "All meals", "Accommodation (lodge/camping mix)"],
    exclusions: ["Tips", "Travel insurance", "Alcoholic beverages"],
    isFeatured: false,
    createdAt: "2026-06-05T08:00:00Z",
    images: tourImages("bale-mountains-wildlife-safari", "Bale Mountains Wildlife Safari"),
  },
  {
    id: "tour-6",
    slug: "axum-gondar-historical-route",
    title: "Axum & Gondar Historical Route",
    destination: "Axum, Gondar",
    category: "historical",
    durationDays: 5,
    groupSizeMax: 14,
    difficulty: "easy",
    price: 42000,
    currency: "ETB",
    summary:
      "Trace Ethiopia's imperial history from the ancient obelisks of Axum to the castles of Gondar, Africa's 'Camelot'.",
    itinerary: [
      { day: 1, title: "Arrival in Axum", description: "Visit the stelae field and the Church of St. Mary of Zion." },
      { day: 2, title: "Axum exploration", description: "Queen of Sheba's Bath, ancient tombs, and the Ezana Stone." },
      { day: 3, title: "Fly to Gondar", description: "Visit the Royal Enclosure and Fasilides' Castle complex." },
      { day: 4, title: "Debre Berhan Selassie & Lake Tana", description: "Visit the painted church, afternoon boat trip to the island monasteries of Lake Tana." },
      { day: 5, title: "Departure", description: "Free morning, transfer to airport." },
    ],
    inclusions: ["Licensed English-speaking guide", "Site entry fees", "Domestic flight Axum–Gondar", "Daily breakfast", "Airport transfers"],
    exclusions: ["Flights to/from Axum and from Gondar", "Lunch & dinner", "Tips", "Travel insurance"],
    isFeatured: false,
    createdAt: "2026-03-30T08:00:00Z",
    images: tourImages("axum-gondar-historical-route", "Axum & Gondar Historical Route"),
  },
];

// ---- reviews ----------------------------------------------------------------

export const mockReviews: Review[] = [
  {
    id: "review-1",
    customerName: "Selamawit T.",
    rating: 5,
    body: "Bought a RAV4 through NUR LA and the whole process was transparent — they showed me the inspection report before I paid anything. Delivered clean and exactly as described.",
    itemLabel: "2022 Toyota RAV4",
    createdAt: "2026-06-20T08:00:00Z",
  },
  {
    id: "review-2",
    customerName: "Dawit K.",
    rating: 5,
    body: "The Simien Mountains trek was the highlight of our trip to Ethiopia. Our guide knew every ridge and the camping setup was better than I expected.",
    itemLabel: "Simien Mountains Trek",
    createdAt: "2026-06-15T08:00:00Z",
  },
  {
    id: "review-3",
    customerName: "Marcus H.",
    rating: 5,
    body: "Danakil was intense but the team's logistics were flawless — never once felt unsafe, even at Erta Ale at night. Worth every birr.",
    itemLabel: "Danakil Depression Expedition",
    createdAt: "2026-06-08T08:00:00Z",
  },
  {
    id: "review-4",
    customerName: "Hanna G.",
    rating: 4,
    body: "Good communication throughout the import process for my Tucson. Took a bit longer than the original estimate but they kept me updated the whole way.",
    itemLabel: "2023 Hyundai Tucson",
    createdAt: "2026-05-28T08:00:00Z",
  },
  {
    id: "review-5",
    customerName: "Yosef A.",
    rating: 5,
    body: "Traded in my old Corolla toward a Land Cruiser Prado — fair valuation, no pressure, and the paperwork was handled for me.",
    itemLabel: "2020 Toyota Land Cruiser Prado",
    createdAt: "2026-05-12T08:00:00Z",
  },
  {
    id: "review-6",
    customerName: "Liya M.",
    rating: 5,
    body: "Lalibela with NUR LA was so well organized — early access before the crowds arrived, and our guide's explanations of the church history were excellent.",
    itemLabel: "Lalibela Rock-Hewn Churches",
    createdAt: "2026-04-30T08:00:00Z",
  },
];
