import type { Car, CarImage, Partner, Review } from "./types";

// Sample content used whenever Supabase env vars aren't configured yet, so
// the site is fully browsable in local/dev/preview before real project
// credentials and inventory are wired up. See README.md.

const angleLabels = [
  "Front Three-Quarter",
  "Side Profile",
  "Rear",
  "Interior — Front Seats",
  "Interior — Dashboard",
  "Detail",
];

export interface PhotoCredit {
  slug: string;
  fileTitle: string;
  url: string;
  sourcePageUrl: string;
  license: string;
  licenseVerified: boolean;
}

// Reference photos for the primary (card) image of each demo car, sourced
// from Wikimedia Commons. Trim/color may differ slightly from the listed
// vehicle — these are mockup/reference photography, not the actual car in
// stock. See app/credits/page.tsx (linked from the footer) for the full,
// visitor-facing attribution required by the CC licenses below; keep that
// page in sync with this list. Entries flagged licenseVerified: false had
// an uncertain license at sourcing time and must be checked on the source
// page before any real production use.
export const photoCredits: PhotoCredit[] = [
  { slug: "toyota-rav4-2022", fileTitle: "Toyota_RAV4_2.5_LTD_HEV_2022.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota_RAV4_2.5_LTD_HEV_2022.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Toyota_RAV4_2.5_LTD_HEV_2022.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "toyota-corolla-2021", fileTitle: "2021_Toyota_Corolla_SE_Hatchback.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Toyota_Corolla_SE_Hatchback.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2021_Toyota_Corolla_SE_Hatchback.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "toyota-land-cruiser-prado-2020", fileTitle: "Toyota_Land_Cruiser_Prado_J150_4.0_VX_2020.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota_Land_Cruiser_Prado_J150_4.0_VX_2020.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Toyota_Land_Cruiser_Prado_J150_4.0_VX_2020.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "hyundai-tucson-2023", fileTitle: "2023_Hyundai_Tucson_Signature_(India)_front_view.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2023_Hyundai_Tucson_Signature_%28India%29_front_view.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2023_Hyundai_Tucson_Signature_(India)_front_view.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "hyundai-i10-2019", fileTitle: "Hyundai_i10_(48813787728).jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Hyundai_i10_%2848813787728%29.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Hyundai_i10_(48813787728).jpg", license: "Unconfirmed — verify on source page before production use", licenseVerified: false },
  { slug: "suzuki-dzire-2021", fileTitle: "Maruti_Suzuki_Dzire_VXi_VVT_(front).JPG", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Maruti_Suzuki_Dzire_VXi_VVT_%28front%29.JPG", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Maruti_Suzuki_Dzire_VXi_VVT_(front).JPG", license: "CC BY 3.0", licenseVerified: true },
  { slug: "suzuki-vitara-2022", fileTitle: "2022_Suzuki_Vitara_1.5_Full_Hybrid.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2022_Suzuki_Vitara_1.5_Full_Hybrid.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2022_Suzuki_Vitara_1.5_Full_Hybrid.jpg", license: "CC BY 2.0", licenseVerified: true },
  { slug: "nissan-xtrail-2020", fileTitle: "2020_Nissan_X-Trail_VL_facelift_(front),_West_Surabaya.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Nissan_X-Trail_VL_facelift_%28front%29%2C_West_Surabaya.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2020_Nissan_X-Trail_VL_facelift_(front),_West_Surabaya.jpg", license: "Unconfirmed — verify on source page before production use", licenseVerified: false },
  { slug: "mitsubishi-pajero-2019", fileTitle: "2019_Mitsubishi_Pajero_Sport_GT-Premium_4WD.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2019_Mitsubishi_Pajero_Sport_GT-Premium_4WD.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2019_Mitsubishi_Pajero_Sport_GT-Premium_4WD.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "lexus-rx350-2021", fileTitle: "Lexus_RX_350_2021.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/Lexus_RX_350_2021.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Lexus_RX_350_2021.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "kia-sportage-2022", fileTitle: "2022_Kia_Sportage.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2022_Kia_Sportage.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2022_Kia_Sportage.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "ford-ranger-2021", fileTitle: "2021_Ford_Ranger_XL,_front_6.1.22.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Ford_Ranger_XL%2C_front_6.1.22.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2021_Ford_Ranger_XL,_front_6.1.22.jpg", license: "CC BY-SA 4.0", licenseVerified: true },
  { slug: "honda-crv-2023", fileTitle: "2023_Honda_CR-V_front_end.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2023_Honda_CR-V_front_end.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2023_Honda_CR-V_front_end.jpg", license: "Unconfirmed — verify on source page before production use", licenseVerified: false },
  { slug: "volkswagen-tiguan-2020", fileTitle: "2020_Volkswagen_Tiguan_au_SIAM_2020.jpg", url: "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Volkswagen_Tiguan_au_SIAM_2020.jpg", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:2020_Volkswagen_Tiguan_au_SIAM_2020.jpg", license: "Public Domain", licenseVerified: true },
];

function images(slug: string, make: string, model: string, year: number): CarImage[] {
  const credit = photoCredits.find((c) => c.slug === slug);
  return angleLabels.map((label, i) => {
    if (i === 0 && credit) {
      return {
        id: `${slug}-img-0`,
        url: credit.url,
        alt: `${year} ${make} ${model} — reference photo (trim/color may vary)`,
        position: 0,
      };
    }
    return {
      id: `${slug}-img-${i}`,
      url: `/cars/${slug}/${i}.svg`,
      alt: `${year} ${make} ${model} — ${label}`,
      position: i,
    };
  });
}

interface CarSeed
  extends Omit<Car, "images" | "createdAt" | "conditionSummary"> {
  daysAgo: number;
  conditionSummary?: string;
}

const defaultCondition =
  "Runs and drives excellently. Fully inspected by our team prior to listing, serviced, and detailed inside and out. Minor cosmetic wear consistent with age and mileage — full details available on request or at viewing.";

const seeds: CarSeed[] = [
  {
    id: "1",
    slug: "toyota-rav4-2022",
    make: "Toyota",
    model: "RAV4",
    trim: "Adventure AWD",
    year: 2022,
    price: 6850000,
    currency: "ETB",
    mileageKm: 28500,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Magnetic Grey",
    interiorColor: "Black leather",
    engine: "2.5L 4-cylinder",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    vin: "JTMW1RFV0ND123456",
    specSheetUrl: "/spec-sheets/toyota-rav4-2022.pdf",
    isFeatured: true,
    daysAgo: 4,
  },
  {
    id: "2",
    slug: "toyota-corolla-2021",
    make: "Toyota",
    model: "Corolla",
    trim: "SE",
    year: 2021,
    price: 4200000,
    currency: "ETB",
    mileageKm: 41200,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "sedan",
    status: "available",
    exteriorColor: "Celestite Grey",
    interiorColor: "Black cloth",
    engine: "1.8L 4-cylinder",
    drivetrain: "FWD",
    seats: 5,
    doors: 4,
    specSheetUrl: "/spec-sheets/toyota-corolla-2021.pdf",
    isFeatured: false,
    daysAgo: 12,
  },
  {
    id: "3",
    slug: "toyota-land-cruiser-prado-2020",
    make: "Toyota",
    model: "Land Cruiser Prado",
    trim: "TX-L",
    year: 2020,
    price: 11500000,
    currency: "ETB",
    mileageKm: 52300,
    fuelType: "diesel",
    transmission: "automatic",
    bodyType: "suv",
    status: "reserved",
    exteriorColor: "Pearl White",
    interiorColor: "Beige leather",
    engine: "2.8L Turbo Diesel",
    drivetrain: "4WD",
    seats: 7,
    doors: 5,
    specSheetUrl: "/spec-sheets/toyota-land-cruiser-prado-2020.pdf",
    isFeatured: true,
    daysAgo: 2,
  },
  {
    id: "4",
    slug: "hyundai-tucson-2023",
    make: "Hyundai",
    model: "Tucson",
    trim: "Limited",
    year: 2023,
    price: 6100000,
    currency: "ETB",
    mileageKm: 15800,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Amazon Grey",
    interiorColor: "Black leather",
    engine: "2.5L 4-cylinder",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    specSheetUrl: "/spec-sheets/hyundai-tucson-2023.pdf",
    isFeatured: true,
    daysAgo: 1,
  },
  {
    id: "5",
    slug: "hyundai-i10-2019",
    make: "Hyundai",
    model: "i10",
    trim: "Magna",
    year: 2019,
    price: 2350000,
    currency: "ETB",
    mileageKm: 63400,
    fuelType: "petrol",
    transmission: "manual",
    bodyType: "hatchback",
    status: "available",
    exteriorColor: "Fiery Red",
    interiorColor: "Grey cloth",
    engine: "1.2L 4-cylinder",
    drivetrain: "FWD",
    seats: 5,
    doors: 5,
    specSheetUrl: "/spec-sheets/hyundai-i10-2019.pdf",
    isFeatured: false,
    daysAgo: 20,
  },
  {
    id: "6",
    slug: "suzuki-dzire-2021",
    make: "Suzuki",
    model: "Dzire",
    trim: "VXI",
    year: 2021,
    price: 3100000,
    currency: "ETB",
    mileageKm: 34700,
    fuelType: "petrol",
    transmission: "manual",
    bodyType: "sedan",
    status: "on_test_drive",
    exteriorColor: "Pearl Arctic White",
    interiorColor: "Beige cloth",
    engine: "1.2L 4-cylinder",
    drivetrain: "FWD",
    seats: 5,
    doors: 4,
    specSheetUrl: "/spec-sheets/suzuki-dzire-2021.pdf",
    isFeatured: false,
    daysAgo: 9,
  },
  {
    id: "7",
    slug: "suzuki-vitara-2022",
    make: "Suzuki",
    model: "Vitara",
    trim: "GLX",
    year: 2022,
    price: 4650000,
    currency: "ETB",
    mileageKm: 22100,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "crossover",
    status: "available",
    exteriorColor: "Speedy Blue",
    interiorColor: "Black cloth",
    engine: "1.6L 4-cylinder",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    specSheetUrl: "/spec-sheets/suzuki-vitara-2022.pdf",
    isFeatured: false,
    daysAgo: 6,
  },
  {
    id: "8",
    slug: "nissan-xtrail-2020",
    make: "Nissan",
    model: "X-Trail",
    trim: "SL",
    year: 2020,
    price: 5400000,
    currency: "ETB",
    mileageKm: 58900,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "sold",
    exteriorColor: "Gun Metallic",
    interiorColor: "Black leather",
    engine: "2.5L 4-cylinder",
    drivetrain: "AWD",
    seats: 7,
    doors: 5,
    specSheetUrl: "/spec-sheets/nissan-xtrail-2020.pdf",
    isFeatured: false,
    daysAgo: 45,
  },
  {
    id: "9",
    slug: "mitsubishi-pajero-2019",
    make: "Mitsubishi",
    model: "Pajero",
    trim: "GLS",
    year: 2019,
    price: 7200000,
    currency: "ETB",
    mileageKm: 71300,
    fuelType: "diesel",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Diamond Black",
    interiorColor: "Grey leather",
    engine: "3.2L Turbo Diesel",
    drivetrain: "4WD",
    seats: 7,
    doors: 5,
    specSheetUrl: "/spec-sheets/mitsubishi-pajero-2019.pdf",
    isFeatured: false,
    daysAgo: 15,
  },
  {
    id: "10",
    slug: "lexus-rx350-2021",
    make: "Lexus",
    model: "RX 350",
    trim: "F Sport",
    year: 2021,
    price: 12900000,
    currency: "ETB",
    mileageKm: 31600,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "reserved",
    exteriorColor: "Nori Green",
    interiorColor: "Black leather",
    engine: "3.5L V6",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    specSheetUrl: "/spec-sheets/lexus-rx350-2021.pdf",
    isFeatured: true,
    daysAgo: 3,
  },
  {
    id: "11",
    slug: "kia-sportage-2022",
    make: "Kia",
    model: "Sportage",
    trim: "EX",
    year: 2022,
    price: 5950000,
    currency: "ETB",
    mileageKm: 19400,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "suv",
    status: "available",
    exteriorColor: "Snow White Pearl",
    interiorColor: "Black leather",
    engine: "2.5L 4-cylinder",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    specSheetUrl: "/spec-sheets/kia-sportage-2022.pdf",
    isFeatured: false,
    daysAgo: 8,
  },
  {
    id: "12",
    slug: "ford-ranger-2021",
    make: "Ford",
    model: "Ranger",
    trim: "XLT",
    year: 2021,
    price: 6700000,
    currency: "ETB",
    mileageKm: 39800,
    fuelType: "diesel",
    transmission: "automatic",
    bodyType: "pickup",
    status: "available",
    exteriorColor: "Meteor Grey",
    interiorColor: "Black cloth",
    engine: "2.0L Bi-Turbo Diesel",
    drivetrain: "4WD",
    seats: 5,
    doors: 4,
    specSheetUrl: "/spec-sheets/ford-ranger-2021.pdf",
    isFeatured: false,
    daysAgo: 11,
  },
  {
    id: "13",
    slug: "honda-crv-2023",
    make: "Honda",
    model: "CR-V",
    trim: "EX-L",
    year: 2023,
    price: 7400000,
    currency: "ETB",
    mileageKm: 0,
    fuelType: "hybrid",
    transmission: "automatic",
    bodyType: "suv",
    status: "coming_soon",
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Black leather",
    engine: "2.0L Hybrid",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    specSheetUrl: "/spec-sheets/honda-crv-2023.pdf",
    isFeatured: true,
    daysAgo: 0,
    conditionSummary:
      "Currently in transit and undergoing pre-listing inspection and detailing. Full condition summary and gallery will be published once it arrives at our showroom.",
  },
  {
    id: "14",
    slug: "volkswagen-tiguan-2020",
    make: "Volkswagen",
    model: "Tiguan",
    trim: "SE",
    year: 2020,
    price: 5100000,
    currency: "ETB",
    mileageKm: 47600,
    fuelType: "petrol",
    transmission: "automatic",
    bodyType: "crossover",
    status: "available",
    exteriorColor: "Deep Black Pearl",
    interiorColor: "Titan Black",
    engine: "2.0L Turbo",
    drivetrain: "AWD",
    seats: 5,
    doors: 5,
    specSheetUrl: "/spec-sheets/volkswagen-tiguan-2020.pdf",
    isFeatured: false,
    daysAgo: 18,
  },
];

export const mockCars: Car[] = seeds.map(({ daysAgo, conditionSummary, ...seed }) => ({
  ...seed,
  conditionSummary: conditionSummary ?? defaultCondition,
  createdAt: new Date(Date.now() - daysAgo * 86400000).toISOString(),
  images: images(seed.slug, seed.make, seed.model, seed.year),
}));

export const mockReviews: Review[] = [
  {
    id: "r1",
    customerName: "Bethlehem A.",
    rating: 5,
    body: "I bought my RAV4 without seeing it in person first — the team sent videos, answered every question, and the car matched the description exactly on pickup. Process was smoother than I expected.",
    carLabel: "2021 Toyota RAV4",
    createdAt: "2026-06-14T09:00:00.000Z",
  },
  {
    id: "r2",
    customerName: "Dawit K.",
    rating: 5,
    body: "Clear pricing, no last-minute surprises on fees, and they handled the import paperwork end to end. Would go through them again for my next car.",
    carLabel: "2020 Toyota Land Cruiser Prado",
    createdAt: "2026-05-02T09:00:00.000Z",
  },
  {
    id: "r3",
    customerName: "Selam T.",
    rating: 4,
    body: "Very responsive on WhatsApp throughout. Test drive was easy to book and the car wash package before delivery was a nice touch.",
    carLabel: "2022 Hyundai Tucson",
    createdAt: "2026-04-20T09:00:00.000Z",
  },
  {
    id: "r4",
    customerName: "Yonas M.",
    rating: 5,
    body: "Traded in my old sedan and they gave a fair valuation with no pressure. The whole thing took about two weeks from first message to driving off.",
    carLabel: "Trade-in customer",
    createdAt: "2026-03-11T09:00:00.000Z",
  },
  {
    id: "r5",
    customerName: "Rahel G.",
    rating: 5,
    body: "What sold me was the honesty about a small paint touch-up on the rear bumper — they mentioned it upfront instead of me finding it later. That's rare.",
    carLabel: "2019 Mitsubishi Pajero",
    createdAt: "2026-02-27T09:00:00.000Z",
  },
  {
    id: "r6",
    customerName: "Nathnael B.",
    rating: 4,
    body: "Good selection and fair prices compared to other importers I checked. Financing partner introduction saved me a lot of running around.",
    carLabel: "2021 Toyota Corolla",
    createdAt: "2026-01-30T09:00:00.000Z",
  },
];

export const mockPartners: Partner[] = [
  { id: "p1", name: "Commercial Bank of Ethiopia", category: "bank" },
  { id: "p2", name: "Awash Bank", category: "bank" },
  { id: "p3", name: "Dashen Bank", category: "bank" },
  { id: "p4", name: "Nyala Insurance", category: "insurer" },
  { id: "p5", name: "Nile Insurance", category: "insurer" },
  { id: "p6", name: "Ethiopian Shipping and Logistics Services", category: "shipper" },
  { id: "p7", name: "Maersk", category: "shipper" },
  { id: "p8", name: "Habesha Insurance", category: "insurer" },
];
